blank_issues_enabled: true
contact_links:
    - name: spacebar Documentation
      url: https://docs.spacebar.chat/
      about: Need documentation and examples for the spacebar? Head over to spacebar's official documentation.
    - name: Discord's Developer Documentation
      url: https://discord.com/developers/docs/intro
      about: Need help with the Discord resources? Head here instead of asking on spacebar!
    - name: spacebar' Official Discord server
      url: https://discord.com/invite/Ms5Ev7S6bF
      about: Need help with the server? Talk with us in our official server.
