name: "tauri publish"
on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libsoup-3.0-dev libjavascriptcoregtk-4.1-dev
      - name: Install Frontend Dependencies
        run: pnpm i
      - name: Run version generator
        run: pnpm run ci:prebuild
      - uses: spacebarchat/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: client-__BRANCH__-v__VERSION__
          releaseName: "spacebar Client v__VERSION__ (__BRANCH__)"
          releaseBody: "See the assets to download this version and install. The current commit is __SHA__."
          releaseDraft: false
          prerelease: true
          includeDebug: true
          includeRelease: true
          includeUpdaterJson: true
